# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-10-18 02:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consecutivo', models.CharField(max_length=10)),
                ('consecutivo_slug', models.SlugField(blank=True, max_length=10, null=True)),
                ('fecha_creacion', models.DateField(blank=True, default=datetime.datetime.now)),
                ('estado', models.IntegerField(choices=[(1, 'No paga'), (2, 'Paga'), (3, 'Anulada/Cancelada')], default=1)),
                ('fecha_actualizacion', models.DateField()),
                ('iva', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FacturaProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidades', models.IntegerField()),
                ('valor_producto_unidad', models.CharField(max_length=20)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidad.Factura')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Producto')),
            ],
        ),
    ]
